# Generated by Django 5.2.6 on 2026-01-10 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_bankaccount_bank_account_overdraft_limit_gte_zero_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='CREATED', max_length=20)),
                ('error_code', models.CharField(blank=True, max_length=100, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions_from', to='accounts.bankaccount')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions_to', to='accounts.bankaccount')),
            ],
            options={
                'indexes': [models.Index(fields=['idempotency_key'], name='transaction_idempot_68455c_idx'), models.Index(fields=['status', 'created_at'], name='transaction_status_d2f80b_idx'), models.Index(fields=['from_account', 'status'], name='transaction_from_ac_a61fed_idx'), models.Index(fields=['to_account', 'status'], name='transaction_to_acco_8ca0c6_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='transaction_amount_positive'), models.CheckConstraint(condition=models.Q(('from_account', models.F('to_account')), _negated=True), name='transaction_different_accounts')],
            },
        ),
    ]
