# Generated by Django 5.2.6 on 2025-12-26 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ledgerentry',
            options={'base_manager_name': 'objects', 'default_manager_name': 'objects'},
        ),
        migrations.RenameIndex(
            model_name='ledgerentry',
            new_name='ledger_ledg_debit_a_89f21f_idx',
            old_name='ledger_ledger_debit_currency_idx',
        ),
        migrations.RenameIndex(
            model_name='ledgerentry',
            new_name='ledger_ledg_credit__21bac5_idx',
            old_name='ledger_ledger_credit_currency_idx',
        ),
    ]
