# Generated by Django 5.2.6 on 2025-12-26 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='account',
            new_name='accounts_ac_currenc_17633c_idx',
            old_name='accounts_acc_currency_idx',
        ),
    ]
