# Generated by Django 5.2.6 on 2026-01-03 04:23

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_accounts_acc_currency_idx_accounts_ac_currenc_17633c_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('RETAIL', 'Retail'), ('BUSINESS', 'Business')], default='RETAIL', max_length=20)),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('FROZEN', 'Frozen'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=20)),
                ('overdraft_limit', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ledger_account', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bank_account', to='accounts.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'status'], name='accounts_ba_user_id_a21fa3_idx'), models.Index(fields=['currency'], name='accounts_ba_currenc_c9c89b_idx')],
            },
        ),
    ]
