# Generated by Django 5.2.6 on 2026-01-03 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_bankaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['currency', 'is_system'], name='accounts_ac_currenc_ec13c9_idx'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(condition=models.Q(('is_system', True)), fields=('currency', 'is_system'), name='unique_system_account_per_currency'),
        ),
    ]
