# Generated by Django 5.2.6 on 2026-01-03 06:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_is_system_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bankaccount',
            constraint=models.CheckConstraint(condition=models.Q(('overdraft_limit__gte', 0)), name='bank_account_overdraft_limit_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='bankaccount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('account_type', 'RETAIL'), ('overdraft_limit', 0)), ('account_type', 'BUSINESS'), _connector='OR'), name='bank_account_retail_no_overdraft'),
        ),
    ]
