# Generated by Django 5.2.9 on 2026-01-14 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_code', models.CharField(max_length=100)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=10)),
                ('decision', models.CharField(choices=[('ALLOW', 'Allow'), ('FLAG', 'Flag'), ('BLOCK', 'Block')], max_length=10)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fraud_events', to='transactions.transaction')),
            ],
            options={
                'indexes': [models.Index(fields=['rule_code'], name='fraud_fraud_rule_co_f8bad7_idx'), models.Index(fields=['risk_level'], name='fraud_fraud_risk_le_1743a6_idx'), models.Index(fields=['decision'], name='fraud_fraud_decisio_791e2d_idx'), models.Index(fields=['created_at'], name='fraud_fraud_created_b337e8_idx')],
                'constraints': [models.UniqueConstraint(fields=('transaction', 'rule_code'), name='unique_rule_per_transaction')],
            },
        ),
    ]
